# fly.toml app configuration file generated for quirrel-redis-metrik on 2024-01-22T22:41:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quirrel-redis-metrik"
primary_region = "iad"

[build]

[mounts]
  source = "redis_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
